//
//  StoriesView.swift
//  VoicesAI
//
//  Created by User on 24/04/24.
//

import SwiftUI

struct StoriesView: View {
    @State private var selectedTopic: Topics = .persahabatan
    @State private var selectedMood: Mood = .bahagia
    @State private var todayStory: String = ""
    
    var body: some View {
        NavigationStack{
            Form{
                // MARK: - PICKER VIEW
                
                Section{
                    Picker(selection: $selectedTopic) {
                        ForEach(Topics.allCases, id: \.self){ topic in Text(topic.rawValue.capitalized)
                                .font(.subheadline)
                                .foregroundStyle(.black)
                        }
                    }label:{
                        Text("Choose topics")
                            .foregroundStyle(.gray)
                    }
                    Picker(selection: $selectedMood) {
                        ForEach(Mood.allCases, id: \.self){ mood in Text(mood.rawValue.capitalized)
                                .font(.subheadline)
                                .foregroundStyle(.black)
                        }
                    }label:{
                        Text("Choose mood")
                            .foregroundStyle(.gray)
                    }
                }
            header: {
                Text("Topics")
            }footer: {
                Text("Choose any topics and mood that you want to listen.")
            }
                // MARK: - TEXT EDITOR
                Section{
                    TextEditor(text: $todayStory)
                        .frame(height: 200)
                        .font(.system(.headline, design: .rounded))
                        .foregroundStyle(.blue)
                    
                }header: {
                    Text("Today Story")
                } footer: {
                    Text("This storie are being generated by Gemini AI.")
                }
                
                // MARK: - BUTTON GENERATE
                Button{
                    //TODO
                }label: {
                    Text("Generate".uppercased())
                        .font(.system(.callout, design: .rounded))
                        .fontWeight(.bold)
                }
                .buttonStyle(PlainButtonStyle())
                .frame(minWidth: 0, maxWidth: .infinity)
                
                
                
            }
            .navigationTitle("Stories")
//            .navigationBarTitleDisplayMode(.inline)
            .tint(.primary)
        }
    }
}
#Preview {
    StoriesView()
}

